language: c

cache:
  directories:
  - "$HOME/.stack"
  - "$HOME/build/serokell/log-warper/.stack-work"

addons:
  apt:
    packages:
    - libgmp-dev

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack --version
  - stack -j 2 setup --no-terminal
  - stack ghc -- --version
  - stack -j 2 build --test --bench --only-snapshot --no-terminal --ghc-options="-Werror"

script:
  - stack --jobs=4 build --test --bench --no-run-benchmarks --no-terminal --ghc-options="-Werror"

notifications:
  email: false
  slack:
    rooms:
      - serokell:bZAMNe9sfjpyLFGIfYnlEmcy
    on_success: change
    on_failure: always