resolver: lts-7.16
compiler: ghc-8.0.2
packages:
- '.'
extra-deps:
- aeson-extra-0.4.0.0
- data-msgpack-0.0.8
- recursion-schemes-5
- time-units-1.0.0
- universum-0.2.1
nix:
  packages: [git, openssh]
flags: {}
extra-package-dbs: []
